general {
    lock_cmd = ~/.config/hypr/scripts/lock-hack.sh
    before_sleep_cmd = ~/.config/hypr/scripts/lock-hack.sh
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = true
}

listener {
    timeout = 300
    on-timeout = ~/.config/hypr/scripts/lock-hack.sh
}

listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
