general {
    hide_cursor = true
}

input-field {
    monitor = DP-2
    size = 200, 52
    outline_thickness = 0
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(0, 0, 0, 0.0)
    inner_color = rgba(0, 0, 0, 0.0)
    font_color = rgba(0, 255, 0, 1.0)
	font_family = Victor Mono SemiBold
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = Input password...
    hide_input = false
    rounding = 0
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = Access denied <b>($ATTEMPTS)</b>
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -520
    halign = center
    valign = center
}
